apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ftp
spec:
  template:
    # 만들어둔 Service Account 이용
    serviceAccountName: operate-workflow-sa
  # 의존하는 이벤트
  dependencies:
  - name: ftp-dep
    eventSourceName: ftp
    eventName: ftp
  triggers:
  - template:
      name: ftp-workflow-trigger
      k8s:
        # ETL 워크플로우 실행
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: ftp-  # 워크플로우 생성 이름 
            spec:
              # 시작 템플릿 지정
              entrypoint: etl
              # 인자값. 설정 (이벤트가 발생될 때 건네진다.)
              arguments:
                parameters:
                - name: config
              # FTP ETL 템플릿을 정의 
              templates:
              - name: etl
                inputs:
                  # 매개변수
                  parameters:
                  - name: config
                container:
                  image: {{ .Values.image }}
                  command: [python]
                  args: ['/etl.py', '{{ "{{" }} inputs.parameters.config {{ "}}" }}']
                  # FTP 사용자 및 암호를 환경변수로 전달 
                  env: 
                  - name: FTP_HOST
                    value: {{ .Values.ftpHost }}
                  - name: FTP_USER
                    value: {{ .Values.ftpUser }}
                  - name: FTP_PASSWD
                    value: {{ .Values.ftpPasswd }}
                  - name: S3_BUCKET 
                    value: {{ .Values.s3Bucket }}
                  - name: S3_PREFIX
                    value: {{ .Values.s3Prefix }}
        # 매개 변수. SNS 이벤트 정보 (Notification) 를 읽어 워크플로우의 인자값을 덮어 씀
        parameters:
        - src:
            dependencyName: ftp-dep
            dataKey: body
          dest: spec.arguments.parameters.0.value
