apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vsftpd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsftpd 
    spec:
      containers:
      - name: vsftpd
        image: fauria/vsftpd 
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30020
        - containerPort: 30021
        env:
        - name: FTP_USER
          value: {{ .Values.ftpUser }}
        - name: FTP_PASS
          value: {{ .Values.ftpPasswd }}
        - name: PASV_ADDRESS_RESOLVE
          value: "YES"
        - name: PASV_ADDR_RESOLVE
          value: "YES"
        - name: PASV_MIN_PORT
          value: "30020"
        - name: PASV_MAX_PORT
          value: "30021"
        - name: PASV_ADDRESS_ENABLE
          value: "YES"
        - name: PASV_ENABLE
          value: "YES"
        - name: LOG_STDOUT
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  labels:
    app.kubernetes.io/name: vsftpd 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: clb
spec:
  selector:
    app.kubernetes.io/name: vsftpd
  ports:
  - name: ftp21
    port: 21
    targetPort: 21
  - name: ftp20
    port: 20
    targetPort: 20
  - name: pasv-min
    port: 30020
    targetPort: 30020
  - name: pasv-max
    port: 30021
    targetPort: 30021
  type: LoadBalancer
---
# # LB 주소 확보되면 vsftpd 환경 변수 지정 
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: get-lb-address
#   annotations:
#     "helm.sh/hook": post-install,post-upgrade
#     "helm.sh/hook-weight": "5"
#     "helm.sh/hook-delete-policy": hook-succeeded 
# spec:
#   template:
#     spec:
#       containers:
#       - name: get-lb-address
#         image: bitnami/kubectl
#         command:
#         - /bin/sh
#         - -c 
#         - |
#           set -e
#           echo "Waiting for LoadBalancer to be ready..."
#           while [ -z "$LB_ADDR" ]; do
#             sleep 5
#             LB_ADDR=$(kubectl get svc vsftpd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
#           done
#           echo "LoadBalancer address: $LB_ADDR"
#           kubectl patch deployment vsftpd -p '{"spec":{"template":{"spec":{"containers":[{"name": "vsftpd","env":[{"name":"PASV_ADDRESS","value":"$LB_ADDR"}]}]}}}}'
#       restartPolicy: OnFailure