apiVersion: batch/v1
kind: Job
metadata:
  name: eks-init
spec:
  template:
    metadata:
      name: eks-init
    spec:
      containers:
      - name: eks-init
        image: eks-init
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.awsAccessKey }}
        - name: AWS_SECRETE_ACCESS_KEY
          value: {{ .Values.awsSecretKey }}
        volumeMounts:
        - name: script-vol
          mountPath: /script
      restartPolicy: Never
      volumes:
      - name: script-vol
        configMap:
          name: script-cm
          defaultMode: 0744
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-cm
data:
  init.sh: |
    echo "Associate OIDC Provider with cluster."
    eksctl utils associate-iam-oidc-provider \
      --region "ap-northeast-2" \
      --cluster prod \
      --approve
    ret=$(aws iam list-policies | grep AWSLoadBalancerControllerIAMPolicy)                                                  if [ -z "$ret" ]; then
      echo "'AWSLoadBalancerControllerIAMPolicy' already exists."
    else
      curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.4.4/docs/install/iam_policy.json
      echo "Create AWSLoadBalancerControllerIAMPolicy."
      aws iam create-policy \
          --policy-name AWSLoadBalancerControllerIAMPolicy \
          --policy-document file://iam_policy.json    
    fi