# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generic_pb2 as generic__pb2


class EventingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartEventSource = channel.unary_stream(
                '/generic.Eventing/StartEventSource',
                request_serializer=generic__pb2.EventSource.SerializeToString,
                response_deserializer=generic__pb2.Event.FromString,
                )


class EventingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartEventSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartEventSource': grpc.unary_stream_rpc_method_handler(
                    servicer.StartEventSource,
                    request_deserializer=generic__pb2.EventSource.FromString,
                    response_serializer=generic__pb2.Event.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generic.Eventing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Eventing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartEventSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/generic.Eventing/StartEventSource',
            generic__pb2.EventSource.SerializeToString,
            generic__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
