apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: minio-etl
requires:
- path: ../infra
build:
  artifacts:
  - image: minio-parq
    context: etl
manifests:
  rawYaml:
  - k8s/*.yaml
resourceSelector:
  allow:
  - groupKind: Sensor.argoproj.io
    image: [".*"]
deploy:
  kubectl:
    hooks:
      after:
      # MinIO 에 etlproj 버킷 생성 
      - host:
          command: ['sh', '-c', "POD=$(kubectl get pods -l 'app.kubernetes.io/instance=minio' -o=jsonpath='{.items[0].metadata.name}') && kubectl exec $POD -- mc alias set my http://localhost:9000 admin adminpass && kubectl exec $POD -- mc mb -p my/etlproj"]
