apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: s3-etl
    context: etl
deploy:
  helm:
    # 패키지 설치전 처리 
    hooks: 
      before:
      - host:
          command: ["sh", "init.sh"]
          os: [darwin, linux]  
    releases:
    - name: s3-setup
      chartPath: setup
      setValueTemplates:
        awsAccessKey: "{{ .AWS_ACCESS_KEY_ID }}"
        awsSecretKey: "{{ .AWS_SECRET_ACCESS_KEY }}"
        project: "{{ .project }}"
        s3bucket: "{{ .s3bucket }}"
        s3prefix: "{{ .s3prefix }}"
