apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: s3-etl
    context: etl
deploy:
  helm:
    # 패키지 설치전 처리 
    hooks: 
      before:
      - host:
          command: ["sh", "init.sh"]
          os: [darwin, linux]  
    releases:
    - name: s3-setup
      chartPath: setup
      # 무한 배포를 막기 위해 변수별 파일 이용 
      valuesFiles:
      - svals/topic-arn.yaml
      - svals/access-key.yaml
      - svals/secret-key.yaml
      - svals/ingress-addr.yaml
      # setValueTemplates:
      #   awsAccessKey: "{{ .AWS_ACCESS_KEY_ID }}"
      #   awsSecretKey: "{{ .AWS_SECRET_ACCESS_KEY }}"
      #   project: "{{ .project }}"
      #   s3bucket: "{{ .s3bucket }}"
      #   s3prefix: "{{ .s3prefix }}"
