apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: s3
build:
  # ETL 코드를 실행할 컨테이너 이미지. `etl` 폴더에 정보가 있다.
  artifacts:
  - image: s3-etl
    context: etl
deploy:
  # 단순 YAML 파일 복사가 아닌, Helm 차트를 통해 배포한다.
  helm:
    # 패키지 설치전 처리 
    hooks: 
      before:
      - host:
          command: ["sh", "init.sh"]
          os: [darwin, linux]  
    releases:
    - name: s3-sns
      chartPath: setup
      # 무한 배포를 막기 위해 변수별 파일 이용 
      valuesFiles:
      - vals/topic-arn.yaml
      - vals/ingress-addr.yaml
      # 빌드 과정에서 생성된 컨테이너 이미지 이름을 변수로 전달한다.
      setValueTemplates:
        image: '{{.IMAGE_FULLY_QUALIFIED_s3_etl}}'
