apiVersion: v1
kind: Pod
metadata:
  name: eks-init
spec:
  containers:
  - name: eks-init
    image: eks-init
    env:
    - name: AWS_ACCESS_KEY_ID
      value: {{ .Values.awsAccessKey }}
    - name: AWS_SECRETE_ACCESS_KEY
      value: {{ .Values.awsSecretKey }}
    volumeMounts:
    - name: script-vol
      mountPath: /
  volumes:
  - name: script-vol
    configMap:
      name: script-cm
      defaultMode: 0744
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-cm
data:
  init.sh: |
    a
    b
    c

