apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: setup
profiles:
  # 로컬 (Minikube) 인프라 설치
- name: local
  manifests:
    rawYaml:
    - k8s/*.yaml
    - local/*.yaml
  deploy:
    helm: 
      # 포트포워딩이 필요한 설치부터 
      releases:
      - name: minio 
        repo: https://charts.bitnami.com/bitnami
        remoteChart: minio 
        setValues:
          auth.rootPassword: adminpass
        wait: true  # 포트포워딩 실패 방지 
      - name: aev 
        repo: https://argoproj.github.io/argo-helm
        remoteChart: argo-events
      - name: awf
        repo: https://charts.bitnami.com/bitnami
        remoteChart: argo-workflows
        setValues:
          auth.enabled: false 
          postgresql.enabled: false
        wait: true  # 포트포워딩 실패 방지 
    # kubectl 로 매니페스트 설치 
    kubectl:
      hooks:
        after:
        # MinIO 에 etlproj 버킷 생성 
        - host:
            command: ['sh', '-c', "POD=$(kubectl get pods -l 'app.kubernetes.io/instance=minio' -o=jsonpath='{.items[0].metadata.name}') && kubectl exec $POD -- mc alias set my http://localhost:9000 admin adminpass && kubectl exec $POD -- mc mb -p my/artifact"]
  # --port-forward 가 잘 동작하지 않아 명시 
  portForward:  
    - resourceType: service 
      resourceName: minio 
      port: 9001
    - resourceType: service
      resourceName: awf-argo-workflows-server
      port: 80
      localPort: 8046
  # AWS EKS 인프라 설치
- name: eks
  manifests:
    rawYaml:
    - k8s/*.yaml
  deploy:
    helm:
      # 패키지 설치전 처리 
      hooks: 
        before:
        - host:
            command: ["sh", "eks/init.sh"]
            os: [darwin, linux]
      releases:
      - name: awslb
        repo: https://aws.github.io/eks-charts
        remoteChart: aws-load-balancer-controller
        namespace: kube-system
        setValueTemplates:
          clusterName: "{{ .EKS_CLUSTER }}"
          serviceAccount.create: false
          serviceAccount.name: aws-load-balancer-controller        
      - name: aev 
        repo: https://argoproj.github.io/argo-helm
        remoteChart: argo-events
      - name: awf
        repo: https://charts.bitnami.com/bitnami
        remoteChart: argo-workflows
        valuesFiles:
        - eks/awf-values.yaml
    kubectl: {}
  