apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: s3
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  sns:
    put:
      # SNS 주제의 ARN3
      topicArn: {{ .Values.topicArn }}
      # 훅은 이벤트소스에서 실행되는 HTTP 서버 설정을 포함하는데, AWS 는 이곳으로 이벤트를 보낸다.
      webhook:
        # 접속 정보
        endpoint: "/"
        port: "12000"
        method: POST
        url: http://{{ .Values.ingressAddr }}:12000
      # AWS 리전
      region: ap-northeast-2